import { Inter } from 'next/font/google'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog Magazine',
  description: 'Generated by Md Nayem Gawhar',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-green-100">
        <NextTopLoader color="#20b15a" height={3} speed={200} />
        {children}
      </body>
    </html>
  )
}
